### PR TITLE
Model preview component

### PR DESCRIPTION
**Pull request by VladislavGritsenko**

### CODE REVIEW

**Comment by VladislavGritsenko** [comment]
TODO: make component responsive

**Comment by VladislavGritsenko** [comment]
Now component looks like i want ^_^

**Comment by Amoki** [comment]
Wow, nice!

Can you revert the direction of the rotation? It feels like scrolling on a mac now :p

**Comment by VladislavGritsenko** [comment]
> Wow, nice!
> 
> Can you revert the direction of the rotation? It feels like scrolling on a mac now :p

Done ^_^

**Pull request merged**
