### PR TITLE
Feature/115 tree remake

### PR DESCRIPTION
**Pull request by VladislavGritsenko**

### CODE REVIEW

**Comment by Amoki** [comment]
Great!
We saw a bug (on project 53 by example) where the tree on the left stuck à the first level (there are subfolders). If we close and open again the free, we see one more level and if we close and open it again, we see one more level, etc!

**Comment by VladislavGritsenko** [comment]
working on it

**Comment by VladislavGritsenko** [comment]
I figure out why this happens. I fix it, but remove animation, because of height caching. Can we leave tree without collapsing animation?

**Comment by Amoki** [comment]
Can you fix the merge conflict?
Then I merge!

**Comment by VladislavGritsenko** [comment]
yes, of course

**Pull request merged**
